[env:hosyond_esp32_4in]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
  lovyan03/LovyanGFX@^1.1.16

build_flags =
  -D LGFX_USE_V1=1
